# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: OpenApiMessages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .OpenApiModelMessages import (
    ProtoOAArchivedSymbol,
    ProtoOAAsset,
    ProtoOAAssetClass,
    ProtoOABonusDepositWithdraw,
    ProtoOAClientPermissionScope,
    ProtoOACtidProfile,
    ProtoOACtidTraderAccount,
    ProtoOADeal,
    ProtoOADealOffset,
    ProtoOADepositWithdraw,
    ProtoOADepthQuote,
    ProtoOADynamicLeverage,
    ProtoOAExecutionType,
    ProtoOAExpectedMargin,
    ProtoOALightSymbol,
    ProtoOAMarginCall,
    ProtoOAOrder,
    ProtoOAOrderTriggerMethod,
    ProtoOAOrderType,
    ProtoOAPayloadType,
    ProtoOAPosition,
    ProtoOAPositionUnrealizedPnL,
    ProtoOAQuoteType,
    ProtoOASymbol,
    ProtoOASymbolCategory,
    ProtoOATickData,
    ProtoOATimeInForce,
    ProtoOATrader,
    ProtoOATradeSide,
    ProtoOATrendbar,
    ProtoOATrendbarPeriod,
)


@dataclass
class ProtoOAApplicationAuthReq(betterproto.Message):
    """
    * Request for the authorizing an application to work with the cTrader
    platform Proxies.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    client_id: str = betterproto.string_field(2)
    client_secret: str = betterproto.string_field(3)


@dataclass
class ProtoOAApplicationAuthRes(betterproto.Message):
    """* Response to the ProtoOAApplicationAuthReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)


@dataclass
class ProtoOAAccountAuthReq(betterproto.Message):
    """
    * Request for authorizing of the trading account session. Requires
    established authorized connection with the client application using
    ProtoOAApplicationAuthReq.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    access_token: str = betterproto.string_field(3)


@dataclass
class ProtoOAAccountAuthRes(betterproto.Message):
    """* Response to the ProtoOAApplicationAuthRes request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAErrorRes(betterproto.Message):
    """* Generic response when an ERROR occurred."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    error_code: str = betterproto.string_field(3)
    description: str = betterproto.string_field(4)
    maintenance_end_timestamp: int = betterproto.int64_field(5)
    retry_after: int = betterproto.uint64_field(6)


@dataclass
class ProtoOAClientDisconnectEvent(betterproto.Message):
    """
    * Event that is sent when the connection with the client application is
    cancelled by the server. All the sessions for the traders' accounts will be
    terminated.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    reason: str = betterproto.string_field(2)


@dataclass
class ProtoOAAccountsTokenInvalidatedEvent(betterproto.Message):
    """
    * Event that is sent when a session to a specific trader's account is
    terminated by the server but the existing connections with the other
    trader's accounts are maintained. Reasons to trigger: account was deleted,
    cTID was deleted, token was refreshed, token was revoked.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_ids: list[int] = betterproto.int64_field(2)
    reason: str = betterproto.string_field(3)


@dataclass
class ProtoOAVersionReq(betterproto.Message):
    """
    * Request for getting the proxy version. Can be used to check the current
    version of the Open API scheme.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)


@dataclass
class ProtoOAVersionRes(betterproto.Message):
    """* Response to the ProtoOAVersionReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    version: str = betterproto.string_field(2)


@dataclass
class ProtoOANewOrderReq(betterproto.Message):
    """
    * Request for sending a new trading order. Allowed only if the accessToken
    has the "trade" permissions for the trading account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: int = betterproto.int64_field(3)
    order_type: "ProtoOAOrderType" = betterproto.enum_field(4)
    trade_side: "ProtoOATradeSide" = betterproto.enum_field(5)
    volume: int = betterproto.int64_field(6)
    limit_price: float = betterproto.double_field(7)
    stop_price: float = betterproto.double_field(8)
    time_in_force: "ProtoOATimeInForce" = betterproto.enum_field(9)
    expiration_timestamp: int = betterproto.int64_field(10)
    stop_loss: float = betterproto.double_field(11)
    take_profit: float = betterproto.double_field(12)
    comment: str = betterproto.string_field(13)
    base_slippage_price: float = betterproto.double_field(14)
    slippage_in_points: int = betterproto.int32_field(15)
    label: str = betterproto.string_field(16)
    position_id: int = betterproto.int64_field(17)
    client_order_id: str = betterproto.string_field(18)
    relative_stop_loss: int = betterproto.int64_field(19)
    relative_take_profit: int = betterproto.int64_field(20)
    guaranteed_stop_loss: bool = betterproto.bool_field(21)
    trailing_stop_loss: bool = betterproto.bool_field(22)
    stop_trigger_method: "ProtoOAOrderTriggerMethod" = betterproto.enum_field(23)


@dataclass
class ProtoOAExecutionEvent(betterproto.Message):
    """
    * Event that is sent following the successful order acceptance or execution
    by the server. Acts as response to the ProtoOANewOrderReq,
    ProtoOACancelOrderReq, ProtoOAAmendOrderReq, ProtoOAAmendPositionSLTPReq,
    ProtoOAClosePositionReq requests. Also, the event is sent when a
    Deposit/Withdrawal took place.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    execution_type: "ProtoOAExecutionType" = betterproto.enum_field(3)
    position: "ProtoOAPosition" = betterproto.message_field(4)
    order: "ProtoOAOrder" = betterproto.message_field(5)
    deal: "ProtoOADeal" = betterproto.message_field(6)
    bonus_deposit_withdraw: "ProtoOABonusDepositWithdraw" = betterproto.message_field(7)
    deposit_withdraw: "ProtoOADepositWithdraw" = betterproto.message_field(8)
    error_code: str = betterproto.string_field(9)
    is_server_event: bool = betterproto.bool_field(10)


@dataclass
class ProtoOACancelOrderReq(betterproto.Message):
    """
    * Request for cancelling existing pending order. Allowed only if the
    accessToken has "trade" permissions for the trading account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    order_id: int = betterproto.int64_field(3)


@dataclass
class ProtoOAAmendOrderReq(betterproto.Message):
    """
    * Request for amending the existing pending order. Allowed only if the
    Access Token has "trade" permissions for the trading account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    order_id: int = betterproto.int64_field(3)
    volume: int = betterproto.int64_field(4)
    limit_price: float = betterproto.double_field(5)
    stop_price: float = betterproto.double_field(6)
    expiration_timestamp: int = betterproto.int64_field(7)
    stop_loss: float = betterproto.double_field(8)
    take_profit: float = betterproto.double_field(9)
    slippage_in_points: int = betterproto.int32_field(10)
    relative_stop_loss: int = betterproto.int64_field(11)
    relative_take_profit: int = betterproto.int64_field(12)
    guaranteed_stop_loss: bool = betterproto.bool_field(13)
    trailing_stop_loss: bool = betterproto.bool_field(14)
    stop_trigger_method: "ProtoOAOrderTriggerMethod" = betterproto.enum_field(15)


@dataclass
class ProtoOAAmendPositionSLTPReq(betterproto.Message):
    """
    * Request for amending StopLoss and TakeProfit of existing position.
    Allowed only if the accessToken has "trade" permissions for the trading
    account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position_id: int = betterproto.int64_field(3)
    stop_loss: float = betterproto.double_field(4)
    take_profit: float = betterproto.double_field(5)
    guaranteed_stop_loss: bool = betterproto.bool_field(7)
    trailing_stop_loss: bool = betterproto.bool_field(8)
    stop_loss_trigger_method: "ProtoOAOrderTriggerMethod" = betterproto.enum_field(9)


@dataclass
class ProtoOAClosePositionReq(betterproto.Message):
    """
    * Request for closing or partially closing of an existing position. Allowed
    only if the accessToken has "trade" permissions for the trading account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position_id: int = betterproto.int64_field(3)
    volume: int = betterproto.int64_field(4)


@dataclass
class ProtoOATrailingSLChangedEvent(betterproto.Message):
    """
    * Event that is sent when the level of the Trailing Stop Loss is changed
    due to the price level changes.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position_id: int = betterproto.int64_field(3)
    order_id: int = betterproto.int64_field(4)
    stop_price: float = betterproto.double_field(5)
    utc_last_update_timestamp: int = betterproto.int64_field(6)


@dataclass
class ProtoOAAssetListReq(betterproto.Message):
    """* Request for the list of assets available for a trader's account."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAAssetListRes(betterproto.Message):
    """* Response to the ProtoOAAssetListReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    asset: list["ProtoOAAsset"] = betterproto.message_field(3)


@dataclass
class ProtoOASymbolsListReq(betterproto.Message):
    """
    * Request for a list of symbols available for a trading account. Symbol
    entries are returned with the limited set of fields.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    include_archived_symbols: bool = betterproto.bool_field(3)


@dataclass
class ProtoOASymbolsListRes(betterproto.Message):
    """* Response to the ProtoOASymbolsListReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol: list["ProtoOALightSymbol"] = betterproto.message_field(3)
    archived_symbol: list["ProtoOAArchivedSymbol"] = betterproto.message_field(4)


@dataclass
class ProtoOASymbolByIdReq(betterproto.Message):
    """* Request for getting a full symbol entity."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: list[int] = betterproto.int64_field(3)


@dataclass
class ProtoOASymbolByIdRes(betterproto.Message):
    """* Response to the ProtoOASymbolByIdReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol: list["ProtoOASymbol"] = betterproto.message_field(3)
    archived_symbol: list["ProtoOAArchivedSymbol"] = betterproto.message_field(4)


@dataclass
class ProtoOASymbolsForConversionReq(betterproto.Message):
    """
    * Request for getting a conversion chain between two assets that consists
    of several symbols. Use when no direct quote is available.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    first_asset_id: int = betterproto.int64_field(3)
    last_asset_id: int = betterproto.int64_field(4)


@dataclass
class ProtoOASymbolsForConversionRes(betterproto.Message):
    """* Response to the ProtoOASymbolsForConversionReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol: list["ProtoOALightSymbol"] = betterproto.message_field(3)


@dataclass
class ProtoOASymbolChangedEvent(betterproto.Message):
    """* Event that is sent when the symbol is changed on the Server side."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: list[int] = betterproto.int64_field(3)


@dataclass
class ProtoOAAssetClassListReq(betterproto.Message):
    """
    * Request for a list of asset classes available for the trader's account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAAssetClassListRes(betterproto.Message):
    """* Response to the ProtoOAAssetListReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    asset_class: list["ProtoOAAssetClass"] = betterproto.message_field(3)


@dataclass
class ProtoOATraderReq(betterproto.Message):
    """* Request for getting data of Trader's Account."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOATraderRes(betterproto.Message):
    """* Response to the ProtoOATraderReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    trader: "ProtoOATrader" = betterproto.message_field(3)


@dataclass
class ProtoOATraderUpdatedEvent(betterproto.Message):
    """* Event that is sent when a Trader is updated on Server side."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    trader: "ProtoOATrader" = betterproto.message_field(3)


@dataclass
class ProtoOAReconcileReq(betterproto.Message):
    """
    * Request for getting Trader's current open positions and pending orders
    data.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    return_protection_orders: bool = betterproto.bool_field(3)


@dataclass
class ProtoOAReconcileRes(betterproto.Message):
    """* The response to the ProtoOAReconcileReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position: list["ProtoOAPosition"] = betterproto.message_field(3)
    order: list["ProtoOAOrder"] = betterproto.message_field(4)


@dataclass
class ProtoOAOrderErrorEvent(betterproto.Message):
    """* Event that is sent when errors occur during the order requests."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(5)
    error_code: str = betterproto.string_field(2)
    order_id: int = betterproto.int64_field(3)
    position_id: int = betterproto.int64_field(6)
    description: str = betterproto.string_field(7)


@dataclass
class ProtoOADealListReq(betterproto.Message):
    """
    * Request for getting Trader's deals historical data (execution details).
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    from_timestamp: int = betterproto.int64_field(3)
    to_timestamp: int = betterproto.int64_field(4)
    max_rows: int = betterproto.int32_field(5)


@dataclass
class ProtoOADealListRes(betterproto.Message):
    """* The response to the ProtoOADealListRes request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    deal: list["ProtoOADeal"] = betterproto.message_field(3)
    has_more: bool = betterproto.bool_field(4)


@dataclass
class ProtoOAOrderListReq(betterproto.Message):
    """* Request for getting Trader's orders filtered by timestamp"""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    from_timestamp: int = betterproto.int64_field(3)
    to_timestamp: int = betterproto.int64_field(4)


@dataclass
class ProtoOAOrderListRes(betterproto.Message):
    """* The response to the ProtoOAOrderListReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    order: list["ProtoOAOrder"] = betterproto.message_field(3)
    has_more: bool = betterproto.bool_field(4)


@dataclass
class ProtoOAExpectedMarginReq(betterproto.Message):
    """
    * Request for getting the margin estimate according to leverage profiles.
    Can be used before sending a new order request. This doesn't consider
    ACCORDING_TO_GSL margin calculation type, as this calculation is trivial:
    usedMargin = (VWAP price of the position - GSL price) * volume *
    Quote2Deposit.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: int = betterproto.int64_field(3)
    volume: list[int] = betterproto.int64_field(4)


@dataclass
class ProtoOAExpectedMarginRes(betterproto.Message):
    """* The response to the ProtoOAExpectedMarginReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    margin: list["ProtoOAExpectedMargin"] = betterproto.message_field(3)
    money_digits: int = betterproto.uint32_field(4)


@dataclass
class ProtoOAMarginChangedEvent(betterproto.Message):
    """
    * Event that is sent when the margin allocated to a specific position is
    changed.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position_id: int = betterproto.uint64_field(3)
    used_margin: int = betterproto.uint64_field(4)
    money_digits: int = betterproto.uint32_field(5)


@dataclass
class ProtoOACashFlowHistoryListReq(betterproto.Message):
    """
    * Request for getting Trader's historical data of deposits and withdrawals.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    from_timestamp: int = betterproto.int64_field(3)
    to_timestamp: int = betterproto.int64_field(4)


@dataclass
class ProtoOACashFlowHistoryListRes(betterproto.Message):
    """* Response to the ProtoOACashFlowHistoryListReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    deposit_withdraw: list["ProtoOADepositWithdraw"] = betterproto.message_field(3)


@dataclass
class ProtoOAGetAccountListByAccessTokenReq(betterproto.Message):
    """
    * Request for getting the list of granted trader's account for the access
    token.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    access_token: str = betterproto.string_field(2)


@dataclass
class ProtoOAGetAccountListByAccessTokenRes(betterproto.Message):
    """* Response to the ProtoOAGetAccountListByAccessTokenReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    access_token: str = betterproto.string_field(2)
    permission_scope: "ProtoOAClientPermissionScope" = betterproto.enum_field(3)
    ctid_trader_account: list["ProtoOACtidTraderAccount"] = betterproto.message_field(4)


@dataclass
class ProtoOARefreshTokenReq(betterproto.Message):
    """
    * Request to refresh the access token using refresh token of granted
    trader's account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    refresh_token: str = betterproto.string_field(2)


@dataclass
class ProtoOARefreshTokenRes(betterproto.Message):
    """* Response to the ProtoOARefreshTokenReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    access_token: str = betterproto.string_field(2)
    token_type: str = betterproto.string_field(3)
    expires_in: int = betterproto.int64_field(4)
    refresh_token: str = betterproto.string_field(5)


@dataclass
class ProtoOASubscribeSpotsReq(betterproto.Message):
    """
    * Request for subscribing on spot events of the specified symbol. After
    successful subscription you'll receive technical ProtoOASpotEvent with
    latest price, after which you'll start receiving updates on prices via
    consequent ProtoOASpotEvents.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: list[int] = betterproto.int64_field(3)
    subscribe_to_spot_timestamp: bool = betterproto.bool_field(4)


@dataclass
class ProtoOASubscribeSpotsRes(betterproto.Message):
    """
    * Response to the ProtoOASubscribeSpotsReq request. Reflects that your
    request to subscribe for symbol has been added to queue. You'll receive
    technical ProtoOASpotEvent with current price shortly after this response.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAUnsubscribeSpotsReq(betterproto.Message):
    """
    * Request for unsubscribing from the spot events of the specified symbol.
    Request to stop receiving ProtoOASpotEvents related to particular symbols.
    Unsubscription is useful to minimize traffic, especially during high
    volatility events.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: list[int] = betterproto.int64_field(3)


@dataclass
class ProtoOAUnsubscribeSpotsRes(betterproto.Message):
    """
    * Response to the ProtoOASubscribeSpotsRes request. Reflects that your
    request to unsubscribe will has been added to queue and will be completed
    shortly. You may still occasionally receive ProtoOASpotEvents until request
    processing is complete.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOASpotEvent(betterproto.Message):
    """
    * Event that is sent when a new spot event is generated on the server side.
    Requires subscription on the spot events, see ProtoOASubscribeSpotsReq.
    First event, received after subscription will contain latest spot prices
    even if market is closed.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: int = betterproto.int64_field(3)
    bid: int = betterproto.uint64_field(4)
    ask: int = betterproto.uint64_field(5)
    trendbar: list["ProtoOATrendbar"] = betterproto.message_field(6)
    session_close: int = betterproto.uint64_field(7)
    timestamp: int = betterproto.int64_field(8)


@dataclass
class ProtoOASubscribeLiveTrendbarReq(betterproto.Message):
    """
    * Request for subscribing for live trend bars. Requires subscription on the
    spot events, see ProtoOASubscribeSpotsReq.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    period: "ProtoOATrendbarPeriod" = betterproto.enum_field(3)
    symbol_id: int = betterproto.int64_field(4)


@dataclass
class ProtoOASubscribeLiveTrendbarRes(betterproto.Message):
    """* Response to the ProtoOASubscribeLiveTrendbarReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAUnsubscribeLiveTrendbarReq(betterproto.Message):
    """* Request for unsubscribing from the live trend bars."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    period: "ProtoOATrendbarPeriod" = betterproto.enum_field(3)
    symbol_id: int = betterproto.int64_field(4)


@dataclass
class ProtoOAUnsubscribeLiveTrendbarRes(betterproto.Message):
    """* Response to the ProtoOASubscribeLiveTrendbarReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAGetTrendbarsReq(betterproto.Message):
    """* Request for getting historical trend bars for the symbol."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    from_timestamp: int = betterproto.int64_field(3)
    to_timestamp: int = betterproto.int64_field(4)
    period: "ProtoOATrendbarPeriod" = betterproto.enum_field(5)
    symbol_id: int = betterproto.int64_field(6)
    count: int = betterproto.uint32_field(7)


@dataclass
class ProtoOAGetTrendbarsRes(betterproto.Message):
    """* Response to the ProtoOAGetTrendbarsReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    period: "ProtoOATrendbarPeriod" = betterproto.enum_field(3)
    timestamp: int = betterproto.int64_field(4)
    trendbar: list["ProtoOATrendbar"] = betterproto.message_field(5)
    symbol_id: int = betterproto.int64_field(6)
    has_more: bool = betterproto.bool_field(7)


@dataclass
class ProtoOAGetTickDataReq(betterproto.Message):
    """* Request for getting historical tick data for the symbol."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: int = betterproto.int64_field(3)
    type: "ProtoOAQuoteType" = betterproto.enum_field(4)
    from_timestamp: int = betterproto.int64_field(5)
    to_timestamp: int = betterproto.int64_field(6)


@dataclass
class ProtoOAGetTickDataRes(betterproto.Message):
    """* Response to the ProtoOAGetTickDataReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    tick_data: list["ProtoOATickData"] = betterproto.message_field(3)
    has_more: bool = betterproto.bool_field(4)


@dataclass
class ProtoOAGetCtidProfileByTokenReq(betterproto.Message):
    """
    * Request for getting details of Trader's profile. Limited due to GDRP
    requirements.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    access_token: str = betterproto.string_field(2)


@dataclass
class ProtoOAGetCtidProfileByTokenRes(betterproto.Message):
    """* Response to the ProtoOAGetCtidProfileByTokenReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    profile: "ProtoOACtidProfile" = betterproto.message_field(2)


@dataclass
class ProtoOADepthEvent(betterproto.Message):
    """
    * Event that is sent when the structure of depth of market is changed.
    Requires subscription on the depth of markets for the symbol, see
    ProtoOASubscribeDepthQuotesReq.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: int = betterproto.uint64_field(3)
    new_quotes: list["ProtoOADepthQuote"] = betterproto.message_field(4)
    deleted_quotes: list[int] = betterproto.uint64_field(5)


@dataclass
class ProtoOASubscribeDepthQuotesReq(betterproto.Message):
    """
    * Request for subscribing on depth of market of the specified symbol.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: list[int] = betterproto.int64_field(3)


@dataclass
class ProtoOASubscribeDepthQuotesRes(betterproto.Message):
    """* Response to the ProtoOASubscribeDepthQuotesReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAUnsubscribeDepthQuotesReq(betterproto.Message):
    """
    * Request for unsubscribing from the depth of market of the specified
    symbol.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_id: list[int] = betterproto.int64_field(3)


@dataclass
class ProtoOAUnsubscribeDepthQuotesRes(betterproto.Message):
    """* Response to the ProtoOAUnsubscribeDepthQuotesReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOASymbolCategoryListReq(betterproto.Message):
    """
    * Request for a list of symbol categories available for a trading account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOASymbolCategoryListRes(betterproto.Message):
    """* Response to the ProtoSymbolCategoryListReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    symbol_category: list["ProtoOASymbolCategory"] = betterproto.message_field(3)


@dataclass
class ProtoOAAccountLogoutReq(betterproto.Message):
    """* Request for logout of trading account session."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAAccountLogoutRes(betterproto.Message):
    """
    * Response to the ProtoOAAccountLogoutReq request. Actual logout of trading
    account will be completed on ProtoOAAccountDisconnectEvent.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAAccountDisconnectEvent(betterproto.Message):
    """
    * Event that is sent when the established session for an account is dropped
    on the server side. A new session must be authorized for the account.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAMarginCallListReq(betterproto.Message):
    """
    * Request for a list of existing margin call thresholds configured for a
    user.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAMarginCallListRes(betterproto.Message):
    """
    * Response with a list of existing user Margin Calls, usually contains 3
    items.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    margin_call: list["ProtoOAMarginCall"] = betterproto.message_field(2)


@dataclass
class ProtoOAMarginCallUpdateReq(betterproto.Message):
    """
    * Request to modify marginLevelThreshold of specified marginCallType for
    ctidTraderAccountId.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    margin_call: "ProtoOAMarginCall" = betterproto.message_field(3)


@dataclass
class ProtoOAMarginCallUpdateRes(betterproto.Message):
    """
    * If this response received, it means that margin call was successfully
    updated.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)


@dataclass
class ProtoOAMarginCallUpdateEvent(betterproto.Message):
    """
    * Event that is sent when a Margin Call threshold configuration is updated.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    margin_call: "ProtoOAMarginCall" = betterproto.message_field(3)


@dataclass
class ProtoOAMarginCallTriggerEvent(betterproto.Message):
    """
    * Event that is sent when account margin level reaches target
    marginLevelThreshold. Event is sent no more than once every 10 minutes to
    avoid spamming.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    margin_call: "ProtoOAMarginCall" = betterproto.message_field(3)


@dataclass
class ProtoOAGetDynamicLeverageByIDReq(betterproto.Message):
    """
    * Request for getting a dynamic leverage entity referenced in
    ProtoOASymbol.leverageId.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    leverage_id: int = betterproto.int64_field(3)


@dataclass
class ProtoOAGetDynamicLeverageByIDRes(betterproto.Message):
    """* Response to the ProtoOAGetDynamicLeverageByIDReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    leverage: "ProtoOADynamicLeverage" = betterproto.message_field(3)


@dataclass
class ProtoOADealListByPositionIdReq(betterproto.Message):
    """* Request for retrieving the deals related to a position."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position_id: int = betterproto.int64_field(3)
    from_timestamp: int = betterproto.int64_field(4)
    to_timestamp: int = betterproto.int64_field(5)


@dataclass
class ProtoOADealListByPositionIdRes(betterproto.Message):
    """* Response to the ProtoOADealListByPositionIdReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    deal: list["ProtoOADeal"] = betterproto.message_field(3)
    has_more: bool = betterproto.bool_field(4)


@dataclass
class ProtoOAOrderDetailsReq(betterproto.Message):
    """* Request for getting Order and its related Deals."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    order_id: int = betterproto.int64_field(3)


@dataclass
class ProtoOAOrderDetailsRes(betterproto.Message):
    """* Response to the ProtoOAOrderDetailsReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    order: "ProtoOAOrder" = betterproto.message_field(3)
    deal: list["ProtoOADeal"] = betterproto.message_field(4)


@dataclass
class ProtoOAOrderListByPositionIdReq(betterproto.Message):
    """
    * Request for retrieving Orders related to a Position by using Position ID.
    Filtered by utcLastUpdateTimestamp.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position_id: int = betterproto.int64_field(3)
    from_timestamp: int = betterproto.int64_field(4)
    to_timestamp: int = betterproto.int64_field(5)


@dataclass
class ProtoOAOrderListByPositionIdRes(betterproto.Message):
    """* Response to ProtoOAOrderListByPositionIdReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    order: list["ProtoOAOrder"] = betterproto.message_field(3)
    has_more: bool = betterproto.bool_field(4)


@dataclass
class ProtoOADealOffsetListReq(betterproto.Message):
    """
    * Request for getting sets of Deals that were offset by a specific Deal and
    that are offsetting the Deal.
    """

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    deal_id: int = betterproto.int64_field(3)


@dataclass
class ProtoOADealOffsetListRes(betterproto.Message):
    """* Response for ProtoOADealOffsetListReq."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    offset_by: list["ProtoOADealOffset"] = betterproto.message_field(3)
    offsetting: list["ProtoOADealOffset"] = betterproto.message_field(4)


@dataclass
class ProtoOAGetPositionUnrealizedPnLReq(betterproto.Message):
    """* Request for getting trader's positions' unrealized PnLs."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)


@dataclass
class ProtoOAGetPositionUnrealizedPnLRes(betterproto.Message):
    """* Response to ProtoOAGetPositionUnrealizedPnLReq request."""

    payload_type: "ProtoOAPayloadType" = betterproto.enum_field(1)
    ctid_trader_account_id: int = betterproto.int64_field(2)
    position_unrealized_pn_l: list["ProtoOAPositionUnrealizedPnL"] = betterproto.message_field(3)
    money_digits: int = betterproto.uint32_field(4)
