# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: OpenApiModelMessages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class ProtoOAPayloadType(betterproto.Enum):
    PROTO_OA_APPLICATION_AUTH_REQ = 2100
    PROTO_OA_APPLICATION_AUTH_RES = 2101
    PROTO_OA_ACCOUNT_AUTH_REQ = 2102
    PROTO_OA_ACCOUNT_AUTH_RES = 2103
    PROTO_OA_VERSION_REQ = 2104
    PROTO_OA_VERSION_RES = 2105
    PROTO_OA_NEW_ORDER_REQ = 2106
    PROTO_OA_TRAILING_SL_CHANGED_EVENT = 2107
    PROTO_OA_CANCEL_ORDER_REQ = 2108
    PROTO_OA_AMEND_ORDER_REQ = 2109
    PROTO_OA_AMEND_POSITION_SLTP_REQ = 2110
    PROTO_OA_CLOSE_POSITION_REQ = 2111
    PROTO_OA_ASSET_LIST_REQ = 2112
    PROTO_OA_ASSET_LIST_RES = 2113
    PROTO_OA_SYMBOLS_LIST_REQ = 2114
    PROTO_OA_SYMBOLS_LIST_RES = 2115
    PROTO_OA_SYMBOL_BY_ID_REQ = 2116
    PROTO_OA_SYMBOL_BY_ID_RES = 2117
    PROTO_OA_SYMBOLS_FOR_CONVERSION_REQ = 2118
    PROTO_OA_SYMBOLS_FOR_CONVERSION_RES = 2119
    PROTO_OA_SYMBOL_CHANGED_EVENT = 2120
    PROTO_OA_TRADER_REQ = 2121
    PROTO_OA_TRADER_RES = 2122
    PROTO_OA_TRADER_UPDATE_EVENT = 2123
    PROTO_OA_RECONCILE_REQ = 2124
    PROTO_OA_RECONCILE_RES = 2125
    PROTO_OA_EXECUTION_EVENT = 2126
    PROTO_OA_SUBSCRIBE_SPOTS_REQ = 2127
    PROTO_OA_SUBSCRIBE_SPOTS_RES = 2128
    PROTO_OA_UNSUBSCRIBE_SPOTS_REQ = 2129
    PROTO_OA_UNSUBSCRIBE_SPOTS_RES = 2130
    PROTO_OA_SPOT_EVENT = 2131
    PROTO_OA_ORDER_ERROR_EVENT = 2132
    PROTO_OA_DEAL_LIST_REQ = 2133
    PROTO_OA_DEAL_LIST_RES = 2134
    PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ = 2135
    PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_REQ = 2136
    PROTO_OA_GET_TRENDBARS_REQ = 2137
    PROTO_OA_GET_TRENDBARS_RES = 2138
    PROTO_OA_EXPECTED_MARGIN_REQ = 2139
    PROTO_OA_EXPECTED_MARGIN_RES = 2140
    PROTO_OA_MARGIN_CHANGED_EVENT = 2141
    PROTO_OA_ERROR_RES = 2142
    PROTO_OA_CASH_FLOW_HISTORY_LIST_REQ = 2143
    PROTO_OA_CASH_FLOW_HISTORY_LIST_RES = 2144
    PROTO_OA_GET_TICKDATA_REQ = 2145
    PROTO_OA_GET_TICKDATA_RES = 2146
    PROTO_OA_ACCOUNTS_TOKEN_INVALIDATED_EVENT = 2147
    PROTO_OA_CLIENT_DISCONNECT_EVENT = 2148
    PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_REQ = 2149
    PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_RES = 2150
    PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_REQ = 2151
    PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_RES = 2152
    PROTO_OA_ASSET_CLASS_LIST_REQ = 2153
    PROTO_OA_ASSET_CLASS_LIST_RES = 2154
    PROTO_OA_DEPTH_EVENT = 2155
    PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_REQ = 2156
    PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_RES = 2157
    PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_REQ = 2158
    PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_RES = 2159
    PROTO_OA_SYMBOL_CATEGORY_REQ = 2160
    PROTO_OA_SYMBOL_CATEGORY_RES = 2161
    PROTO_OA_ACCOUNT_LOGOUT_REQ = 2162
    PROTO_OA_ACCOUNT_LOGOUT_RES = 2163
    PROTO_OA_ACCOUNT_DISCONNECT_EVENT = 2164
    PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_RES = 2165
    PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_RES = 2166
    PROTO_OA_MARGIN_CALL_LIST_REQ = 2167
    PROTO_OA_MARGIN_CALL_LIST_RES = 2168
    PROTO_OA_MARGIN_CALL_UPDATE_REQ = 2169
    PROTO_OA_MARGIN_CALL_UPDATE_RES = 2170
    PROTO_OA_MARGIN_CALL_UPDATE_EVENT = 2171
    PROTO_OA_MARGIN_CALL_TRIGGER_EVENT = 2172
    PROTO_OA_REFRESH_TOKEN_REQ = 2173
    PROTO_OA_REFRESH_TOKEN_RES = 2174
    PROTO_OA_ORDER_LIST_REQ = 2175
    PROTO_OA_ORDER_LIST_RES = 2176
    PROTO_OA_GET_DYNAMIC_LEVERAGE_REQ = 2177
    PROTO_OA_GET_DYNAMIC_LEVERAGE_RES = 2178
    PROTO_OA_DEAL_LIST_BY_POSITION_ID_REQ = 2179
    PROTO_OA_DEAL_LIST_BY_POSITION_ID_RES = 2180
    PROTO_OA_ORDER_DETAILS_REQ = 2181
    PROTO_OA_ORDER_DETAILS_RES = 2182
    PROTO_OA_ORDER_LIST_BY_POSITION_ID_REQ = 2183
    PROTO_OA_ORDER_LIST_BY_POSITION_ID_RES = 2184
    PROTO_OA_DEAL_OFFSET_LIST_REQ = 2185
    PROTO_OA_DEAL_OFFSET_LIST_RES = 2186
    PROTO_OA_GET_POSITION_UNREALIZED_PNL_REQ = 2187
    PROTO_OA_GET_POSITION_UNREALIZED_PNL_RES = 2188


class ProtoOADayOfWeek(betterproto.Enum):
    NONE = 0
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7


class ProtoOACommissionType(betterproto.Enum):
    """* Enum for specifying type of trading commission."""

    USD_PER_MILLION_USD = 1
    USD_PER_LOT = 2
    PERCENTAGE_OF_VALUE = 3
    QUOTE_CCY_PER_LOT = 4


class ProtoOASymbolDistanceType(betterproto.Enum):
    """* Enum for specifying stop loss and take profit distances."""

    SYMBOL_DISTANCE_IN_POINTS = 1
    SYMBOL_DISTANCE_IN_PERCENTAGE = 2


class ProtoOAMinCommissionType(betterproto.Enum):
    """* Enum for specifying type of minimum trading commission."""

    CURRENCY = 1
    QUOTE_CURRENCY = 2


class ProtoOATradingMode(betterproto.Enum):
    """* Enum for specifying symbol trading mode."""

    ENABLED = 0
    DISABLED_WITHOUT_PENDINGS_EXECUTION = 1
    DISABLED_WITH_PENDINGS_EXECUTION = 2
    CLOSE_ONLY_MODE = 3


class ProtoOASwapCalculationType(betterproto.Enum):
    """* Enum for specifying SWAP calculation type for symbol."""

    PIPS = 0
    PERCENTAGE = 1
    POINTS = 2


class ProtoOAAccessRights(betterproto.Enum):
    """* Enum for specifying access right for a trader."""

    FULL_ACCESS = 0
    CLOSE_ONLY = 1
    NO_TRADING = 2
    NO_LOGIN = 3


class ProtoOATotalMarginCalculationType(betterproto.Enum):
    """* Enum for specifying margin calculation type for an account."""

    MAX = 0
    SUM = 1
    NET = 2


class ProtoOAAccountType(betterproto.Enum):
    """* Enum for specifying type of an account."""

    HEDGED = 0
    NETTED = 1
    SPREAD_BETTING = 2


class ProtoOAPositionStatus(betterproto.Enum):
    """* Position status ENUM."""

    POSITION_STATUS_OPEN = 1
    POSITION_STATUS_CLOSED = 2
    POSITION_STATUS_CREATED = 3
    POSITION_STATUS_ERROR = 4


class ProtoOATradeSide(betterproto.Enum):
    """* Trader side ENUM. Used for order, position, deal."""

    BUY = 1
    SELL = 2


class ProtoOAOrderType(betterproto.Enum):
    """* Order type ENUM."""

    MARKET = 1
    LIMIT = 2
    STOP = 3
    STOP_LOSS_TAKE_PROFIT = 4
    MARKET_RANGE = 5
    STOP_LIMIT = 6


class ProtoOATimeInForce(betterproto.Enum):
    """* Order's time in force ENUM."""

    GOOD_TILL_DATE = 1
    GOOD_TILL_CANCEL = 2
    IMMEDIATE_OR_CANCEL = 3
    FILL_OR_KILL = 4
    MARKET_ON_OPEN = 5


class ProtoOAOrderStatus(betterproto.Enum):
    """* Order status ENUM."""

    ORDER_STATUS_ACCEPTED = 1
    ORDER_STATUS_FILLED = 2
    ORDER_STATUS_REJECTED = 3
    ORDER_STATUS_EXPIRED = 4
    ORDER_STATUS_CANCELLED = 5


class ProtoOAOrderTriggerMethod(betterproto.Enum):
    """* Stop Order and Stop Loss triggering method ENUM."""

    TRADE = 1
    OPPOSITE = 2
    DOUBLE_TRADE = 3
    DOUBLE_OPPOSITE = 4


class ProtoOAExecutionType(betterproto.Enum):
    """* Execution event type ENUM."""

    ORDER_ACCEPTED = 2
    ORDER_FILLED = 3
    ORDER_REPLACED = 4
    ORDER_CANCELLED = 5
    ORDER_EXPIRED = 6
    ORDER_REJECTED = 7
    ORDER_CANCEL_REJECTED = 8
    SWAP = 9
    DEPOSIT_WITHDRAW = 10
    ORDER_PARTIAL_FILL = 11
    BONUS_DEPOSIT_WITHDRAW = 12


class ProtoOAChangeBonusType(betterproto.Enum):
    """* Bonus operation type ENUM."""

    BONUS_DEPOSIT = 0
    BONUS_WITHDRAW = 1


class ProtoOAChangeBalanceType(betterproto.Enum):
    """
    * Balance operation entity. Covers all cash movement operations related to
    account, trading, IB operations, mirroring, etc.
    """

    BALANCE_DEPOSIT = 0
    BALANCE_WITHDRAW = 1
    BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER = 3
    BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER = 4
    BALANCE_DEPOSIT_IB_COMMISSIONS = 5
    BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE = 6
    BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB = 7
    BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER = 8
    BALANCE_DEPOSIT_REBATE = 9
    BALANCE_WITHDRAW_REBATE = 10
    BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER = 11
    BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER = 12
    BALANCE_WITHDRAW_BONUS_COMPENSATION = 13
    BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER = 14
    BALANCE_DEPOSIT_DIVIDENDS = 15
    BALANCE_WITHDRAW_DIVIDENDS = 16
    BALANCE_WITHDRAW_GSL_CHARGE = 17
    BALANCE_WITHDRAW_ROLLOVER = 18
    BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS = 19
    BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS = 20
    BALANCE_DEPOSIT_SWAP = 21
    BALANCE_WITHDRAW_SWAP = 22
    BALANCE_DEPOSIT_MANAGEMENT_FEE = 27
    BALANCE_WITHDRAW_MANAGEMENT_FEE = 28
    BALANCE_DEPOSIT_PERFORMANCE_FEE = 29
    BALANCE_WITHDRAW_FOR_SUBACCOUNT = 30
    BALANCE_DEPOSIT_TO_SUBACCOUNT = 31
    BALANCE_WITHDRAW_FROM_SUBACCOUNT = 32
    BALANCE_DEPOSIT_FROM_SUBACCOUNT = 33
    BALANCE_WITHDRAW_COPY_FEE = 34
    BALANCE_WITHDRAW_INACTIVITY_FEE = 35
    BALANCE_DEPOSIT_TRANSFER = 36
    BALANCE_WITHDRAW_TRANSFER = 37
    BALANCE_DEPOSIT_CONVERTED_BONUS = 38
    BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION = 39


class ProtoOADealStatus(betterproto.Enum):
    """* Deal status ENUM."""

    FILLED = 2
    PARTIALLY_FILLED = 3
    REJECTED = 4
    INTERNALLY_REJECTED = 5
    ERROR = 6
    MISSED = 7


class ProtoOATrendbarPeriod(betterproto.Enum):
    """* Trendbar period ENUM."""

    M1 = 1
    M2 = 2
    M3 = 3
    M4 = 4
    M5 = 5
    M10 = 6
    M15 = 7
    M30 = 8
    H1 = 9
    H4 = 10
    H12 = 11
    D1 = 12
    W1 = 13
    MN1 = 14


class ProtoOAQuoteType(betterproto.Enum):
    """* Price quote type."""

    BID = 1
    ASK = 2


class ProtoOAClientPermissionScope(betterproto.Enum):
    """* Open API application permission in regards to token ENUM."""

    SCOPE_VIEW = 0
    SCOPE_TRADE = 1


class ProtoOANotificationType(betterproto.Enum):
    """
    * Type of notification, currently only 3 instances of marginCall are
    supported.
    """

    MARGIN_LEVEL_THRESHOLD_1 = 61
    MARGIN_LEVEL_THRESHOLD_2 = 62
    MARGIN_LEVEL_THRESHOLD_3 = 63


class ProtoOAErrorCode(betterproto.Enum):
    """* Error code ENUM."""

    # Authorization
    OA_AUTH_TOKEN_EXPIRED = 1
    ACCOUNT_NOT_AUTHORIZED = 2
    RET_NO_SUCH_LOGIN = 12
    ALREADY_LOGGED_IN = 14
    RET_ACCOUNT_DISABLED = 64
    CH_CLIENT_AUTH_FAILURE = 101
    CH_CLIENT_NOT_AUTHENTICATED = 102
    CH_CLIENT_ALREADY_AUTHENTICATED = 103
    CH_ACCESS_TOKEN_INVALID = 104
    CH_SERVER_NOT_REACHABLE = 105
    CH_CTID_TRADER_ACCOUNT_NOT_FOUND = 106
    CH_OA_CLIENT_NOT_FOUND = 107
    # General
    REQUEST_FREQUENCY_EXCEEDED = 108
    SERVER_IS_UNDER_MAINTENANCE = 109
    CHANNEL_IS_BLOCKED = 110
    CONNECTIONS_LIMIT_EXCEEDED = 67
    WORSE_GSL_NOT_ALLOWED = 68
    SYMBOL_HAS_HOLIDAY = 69
    # Pricing
    NOT_SUBSCRIBED_TO_SPOTS = 112
    ALREADY_SUBSCRIBED = 113
    SYMBOL_NOT_FOUND = 114
    UNKNOWN_SYMBOL = 115
    INCORRECT_BOUNDARIES = 35
    # Trading
    NO_QUOTES = 117
    NOT_ENOUGH_MONEY = 118
    MAX_EXPOSURE_REACHED = 119
    POSITION_NOT_FOUND = 120
    ORDER_NOT_FOUND = 121
    POSITION_NOT_OPEN = 122
    POSITION_LOCKED = 123
    TOO_MANY_POSITIONS = 124
    TRADING_BAD_VOLUME = 125
    TRADING_BAD_STOPS = 126
    TRADING_BAD_PRICES = 127
    TRADING_BAD_STAKE = 128
    PROTECTION_IS_TOO_CLOSE_TO_MARKET = 129
    TRADING_BAD_EXPIRATION_DATE = 130
    PENDING_EXECUTION = 131
    TRADING_DISABLED = 132
    TRADING_NOT_ALLOWED = 133
    UNABLE_TO_CANCEL_ORDER = 134
    UNABLE_TO_AMEND_ORDER = 135
    SHORT_SELLING_NOT_ALLOWED = 136


class ProtoOALimitedRiskMarginCalculationStrategy(betterproto.Enum):
    ACCORDING_TO_LEVERAGE = 0
    ACCORDING_TO_GSL = 1
    ACCORDING_TO_GSL_AND_LEVERAGE = 2


class ProtoOAStopOutStrategy(betterproto.Enum):
    MOST_MARGIN_USED_FIRST = 0
    MOST_LOSING_FIRST = 1


@dataclass
class ProtoOAAsset(betterproto.Message):
    """* Asset entity."""

    asset_id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    display_name: str = betterproto.string_field(3)
    digits: int = betterproto.int32_field(4)


@dataclass
class ProtoOASymbol(betterproto.Message):
    """* Trading symbol entity."""

    symbol_id: int = betterproto.int64_field(1)
    digits: int = betterproto.int32_field(2)
    pip_position: int = betterproto.int32_field(3)
    enable_short_selling: bool = betterproto.bool_field(4)
    guaranteed_stop_loss: bool = betterproto.bool_field(5)
    swap_rollover3_days: "ProtoOADayOfWeek" = betterproto.enum_field(6)
    swap_long: float = betterproto.double_field(7)
    swap_short: float = betterproto.double_field(8)
    max_volume: int = betterproto.int64_field(9)
    min_volume: int = betterproto.int64_field(10)
    step_volume: int = betterproto.int64_field(11)
    max_exposure: int = betterproto.uint64_field(12)
    schedule: list["ProtoOAInterval"] = betterproto.message_field(13)
    commission: int = betterproto.int64_field(14)
    commission_type: "ProtoOACommissionType" = betterproto.enum_field(15)
    sl_distance: int = betterproto.uint32_field(16)
    tp_distance: int = betterproto.uint32_field(17)
    gsl_distance: int = betterproto.uint32_field(18)
    gsl_charge: int = betterproto.int64_field(19)
    distance_set_in: "ProtoOASymbolDistanceType" = betterproto.enum_field(20)
    min_commission: int = betterproto.int64_field(21)
    min_commission_type: "ProtoOAMinCommissionType" = betterproto.enum_field(22)
    min_commission_asset: str = betterproto.string_field(23)
    rollover_commission: int = betterproto.int64_field(24)
    skip_rollover_days: int = betterproto.int32_field(25)
    schedule_time_zone: str = betterproto.string_field(26)
    trading_mode: "ProtoOATradingMode" = betterproto.enum_field(27)
    rollover_commission3_days: "ProtoOADayOfWeek" = betterproto.enum_field(28)
    swap_calculation_type: "ProtoOASwapCalculationType" = betterproto.enum_field(29)
    lot_size: int = betterproto.int64_field(30)
    precise_trading_commission_rate: int = betterproto.int64_field(31)
    precise_min_commission: int = betterproto.int64_field(32)
    holiday: list["ProtoOAHoliday"] = betterproto.message_field(33)
    pnl_conversion_fee_rate: int = betterproto.int32_field(34)
    leverage_id: int = betterproto.int64_field(35)
    swap_period: int = betterproto.int32_field(36)
    swap_time: int = betterproto.int32_field(37)
    skip_s_w_a_p_periods: int = betterproto.int32_field(38)
    charge_swap_at_weekends: bool = betterproto.bool_field(39)
    measurement_units: str = betterproto.string_field(40)


@dataclass
class ProtoOALightSymbol(betterproto.Message):
    """* Lightweight symbol entity."""

    symbol_id: int = betterproto.int64_field(1)
    symbol_name: str = betterproto.string_field(2)
    enabled: bool = betterproto.bool_field(3)
    base_asset_id: int = betterproto.int64_field(4)
    quote_asset_id: int = betterproto.int64_field(5)
    symbol_category_id: int = betterproto.int64_field(6)
    description: str = betterproto.string_field(7)
    sorting_number: float = betterproto.double_field(8)


@dataclass
class ProtoOAArchivedSymbol(betterproto.Message):
    symbol_id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    utc_last_update_timestamp: int = betterproto.int64_field(3)
    description: str = betterproto.string_field(4)


@dataclass
class ProtoOASymbolCategory(betterproto.Message):
    """* Symbol category entity."""

    id: int = betterproto.int64_field(1)
    asset_class_id: int = betterproto.int64_field(2)
    name: str = betterproto.string_field(3)
    sorting_number: float = betterproto.double_field(4)


@dataclass
class ProtoOAInterval(betterproto.Message):
    """* Symbol trading session entity."""

    start_second: int = betterproto.uint32_field(3)
    end_second: int = betterproto.uint32_field(4)


@dataclass
class ProtoOATrader(betterproto.Message):
    """* Trading account entity."""

    ctid_trader_account_id: int = betterproto.int64_field(1)
    balance: int = betterproto.int64_field(2)
    balance_version: int = betterproto.int64_field(3)
    manager_bonus: int = betterproto.int64_field(4)
    ib_bonus: int = betterproto.int64_field(5)
    non_withdrawable_bonus: int = betterproto.int64_field(6)
    access_rights: "ProtoOAAccessRights" = betterproto.enum_field(7)
    deposit_asset_id: int = betterproto.int64_field(8)
    swap_free: bool = betterproto.bool_field(9)
    leverage_in_cents: int = betterproto.uint32_field(10)
    total_margin_calculation_type: "ProtoOATotalMarginCalculationType" = betterproto.enum_field(11)
    max_leverage: int = betterproto.uint32_field(12)
    french_risk: bool = betterproto.bool_field(13)
    trader_login: int = betterproto.int64_field(14)
    account_type: "ProtoOAAccountType" = betterproto.enum_field(15)
    broker_name: str = betterproto.string_field(16)
    registration_timestamp: int = betterproto.int64_field(17)
    is_limited_risk: bool = betterproto.bool_field(18)
    limited_risk_margin_calculation_strategy: "ProtoOALimitedRiskMarginCalculationStrategy" = betterproto.enum_field(19)
    money_digits: int = betterproto.uint32_field(20)
    fair_stop_out: bool = betterproto.bool_field(21)
    stop_out_strategy: "ProtoOAStopOutStrategy" = betterproto.enum_field(22)


@dataclass
class ProtoOAPosition(betterproto.Message):
    """* Trade position entity."""

    position_id: int = betterproto.int64_field(1)
    trade_data: "ProtoOATradeData" = betterproto.message_field(2)
    position_status: "ProtoOAPositionStatus" = betterproto.enum_field(3)
    swap: int = betterproto.int64_field(4)
    price: float = betterproto.double_field(5)
    stop_loss: float = betterproto.double_field(6)
    take_profit: float = betterproto.double_field(7)
    utc_last_update_timestamp: int = betterproto.int64_field(8)
    commission: int = betterproto.int64_field(9)
    margin_rate: float = betterproto.double_field(10)
    mirroring_commission: int = betterproto.int64_field(11)
    guaranteed_stop_loss: bool = betterproto.bool_field(12)
    used_margin: int = betterproto.uint64_field(13)
    stop_loss_trigger_method: "ProtoOAOrderTriggerMethod" = betterproto.enum_field(14)
    money_digits: int = betterproto.uint32_field(15)
    trailing_stop_loss: bool = betterproto.bool_field(16)


@dataclass
class ProtoOATradeData(betterproto.Message):
    """* Position/order trading details entity."""

    symbol_id: int = betterproto.int64_field(1)
    volume: int = betterproto.int64_field(2)
    trade_side: "ProtoOATradeSide" = betterproto.enum_field(3)
    open_timestamp: int = betterproto.int64_field(4)
    label: str = betterproto.string_field(5)
    guaranteed_stop_loss: bool = betterproto.bool_field(6)
    comment: str = betterproto.string_field(7)
    measurement_units: str = betterproto.string_field(8)
    close_timestamp: int = betterproto.uint64_field(9)


@dataclass
class ProtoOAOrder(betterproto.Message):
    """* Trade order entity."""

    order_id: int = betterproto.int64_field(1)
    trade_data: "ProtoOATradeData" = betterproto.message_field(2)
    order_type: "ProtoOAOrderType" = betterproto.enum_field(3)
    order_status: "ProtoOAOrderStatus" = betterproto.enum_field(4)
    expiration_timestamp: int = betterproto.int64_field(6)
    execution_price: float = betterproto.double_field(7)
    executed_volume: int = betterproto.int64_field(8)
    utc_last_update_timestamp: int = betterproto.int64_field(9)
    base_slippage_price: float = betterproto.double_field(10)
    slippage_in_points: int = betterproto.int64_field(11)
    closing_order: bool = betterproto.bool_field(12)
    limit_price: float = betterproto.double_field(13)
    stop_price: float = betterproto.double_field(14)
    stop_loss: float = betterproto.double_field(15)
    take_profit: float = betterproto.double_field(16)
    client_order_id: str = betterproto.string_field(17)
    time_in_force: "ProtoOATimeInForce" = betterproto.enum_field(18)
    position_id: int = betterproto.int64_field(19)
    relative_stop_loss: int = betterproto.int64_field(20)
    relative_take_profit: int = betterproto.int64_field(21)
    is_stop_out: bool = betterproto.bool_field(22)
    trailing_stop_loss: bool = betterproto.bool_field(23)
    stop_trigger_method: "ProtoOAOrderTriggerMethod" = betterproto.enum_field(24)


@dataclass
class ProtoOABonusDepositWithdraw(betterproto.Message):
    """* Bonus deposit/withdrawal entity."""

    operation_type: "ProtoOAChangeBonusType" = betterproto.enum_field(1)
    bonus_history_id: int = betterproto.int64_field(2)
    manager_bonus: int = betterproto.int64_field(3)
    manager_delta: int = betterproto.int64_field(4)
    ib_bonus: int = betterproto.int64_field(5)
    ib_delta: int = betterproto.int64_field(6)
    change_bonus_timestamp: int = betterproto.int64_field(7)
    external_note: str = betterproto.string_field(8)
    introducing_broker_id: int = betterproto.int64_field(9)
    money_digits: int = betterproto.uint32_field(10)


@dataclass
class ProtoOADepositWithdraw(betterproto.Message):
    """* Account deposit/withdrawal operation entity."""

    operation_type: "ProtoOAChangeBalanceType" = betterproto.enum_field(1)
    balance_history_id: int = betterproto.int64_field(2)
    balance: int = betterproto.int64_field(3)
    delta: int = betterproto.int64_field(4)
    change_balance_timestamp: int = betterproto.int64_field(5)
    external_note: str = betterproto.string_field(6)
    balance_version: int = betterproto.int64_field(7)
    equity: int = betterproto.int64_field(8)
    money_digits: int = betterproto.uint32_field(9)


@dataclass
class ProtoOADeal(betterproto.Message):
    """* Execution entity."""

    deal_id: int = betterproto.int64_field(1)
    order_id: int = betterproto.int64_field(2)
    position_id: int = betterproto.int64_field(3)
    volume: int = betterproto.int64_field(4)
    filled_volume: int = betterproto.int64_field(5)
    symbol_id: int = betterproto.int64_field(6)
    create_timestamp: int = betterproto.int64_field(7)
    execution_timestamp: int = betterproto.int64_field(8)
    utc_last_update_timestamp: int = betterproto.int64_field(9)
    execution_price: float = betterproto.double_field(10)
    trade_side: "ProtoOATradeSide" = betterproto.enum_field(11)
    deal_status: "ProtoOADealStatus" = betterproto.enum_field(12)
    margin_rate: float = betterproto.double_field(13)
    commission: int = betterproto.int64_field(14)
    base_to_usd_conversion_rate: float = betterproto.double_field(15)
    close_position_detail: "ProtoOAClosePositionDetail" = betterproto.message_field(16)
    money_digits: int = betterproto.uint32_field(17)


@dataclass
class ProtoOADealOffset(betterproto.Message):
    """* Deal details for ProtoOADealOffsetListReq."""

    deal_id: int = betterproto.int64_field(1)
    volume: int = betterproto.int64_field(2)
    execution_timestamp: int = betterproto.int64_field(3)
    execution_price: float = betterproto.double_field(4)


@dataclass
class ProtoOAClosePositionDetail(betterproto.Message):
    """* Trading details for closing deal."""

    entry_price: float = betterproto.double_field(1)
    gross_profit: int = betterproto.int64_field(2)
    swap: int = betterproto.int64_field(3)
    commission: int = betterproto.int64_field(4)
    balance: int = betterproto.int64_field(5)
    quote_to_deposit_conversion_rate: float = betterproto.double_field(6)
    closed_volume: int = betterproto.int64_field(7)
    balance_version: int = betterproto.int64_field(8)
    money_digits: int = betterproto.uint32_field(9)
    pnl_conversion_fee: int = betterproto.int64_field(10)


@dataclass
class ProtoOATrendbar(betterproto.Message):
    """* Historical Trendbar entity."""

    volume: int = betterproto.int64_field(3)
    period: "ProtoOATrendbarPeriod" = betterproto.enum_field(4)
    low: int = betterproto.int64_field(5)
    delta_open: int = betterproto.uint64_field(6)
    delta_close: int = betterproto.uint64_field(7)
    delta_high: int = betterproto.uint64_field(8)
    utc_timestamp_in_minutes: int = betterproto.uint32_field(9)


@dataclass
class ProtoOAExpectedMargin(betterproto.Message):
    """* Expected margin computation entity."""

    volume: int = betterproto.int64_field(1)
    buy_margin: int = betterproto.int64_field(2)
    sell_margin: int = betterproto.int64_field(3)


@dataclass
class ProtoOATickData(betterproto.Message):
    """* Historical tick data type."""

    timestamp: int = betterproto.int64_field(1)
    tick: int = betterproto.int64_field(2)


@dataclass
class ProtoOACtidProfile(betterproto.Message):
    """* Trader profile entity. Empty due to GDPR."""

    user_id: int = betterproto.int64_field(1)


@dataclass
class ProtoOACtidTraderAccount(betterproto.Message):
    """* Trader account entity."""

    ctid_trader_account_id: int = betterproto.uint64_field(1)
    is_live: bool = betterproto.bool_field(2)
    trader_login: int = betterproto.int64_field(3)
    last_closing_deal_timestamp: int = betterproto.int64_field(4)
    last_balance_update_timestamp: int = betterproto.int64_field(5)
    broker_title_short: str = betterproto.string_field(6)


@dataclass
class ProtoOAAssetClass(betterproto.Message):
    """* Asset class entity."""

    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    sorting_number: float = betterproto.double_field(3)


@dataclass
class ProtoOADepthQuote(betterproto.Message):
    """* Depth of market entity."""

    id: int = betterproto.uint64_field(1)
    size: int = betterproto.uint64_field(3)
    bid: int = betterproto.uint64_field(4)
    ask: int = betterproto.uint64_field(5)


@dataclass
class ProtoOAMarginCall(betterproto.Message):
    """
    * Margin call entity, specifies threshold for exact margin call type. Only
    3 instances of margin calls are supported, identified by marginCallType.
    See ProtoOANotificationType for details.
    """

    margin_call_type: "ProtoOANotificationType" = betterproto.enum_field(1)
    margin_level_threshold: float = betterproto.double_field(2)
    utc_last_update_timestamp: int = betterproto.int64_field(3)


@dataclass
class ProtoOAHoliday(betterproto.Message):
    holiday_id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    schedule_time_zone: str = betterproto.string_field(4)
    holiday_date: int = betterproto.int64_field(5)
    is_recurring: bool = betterproto.bool_field(6)
    start_second: int = betterproto.int32_field(7)
    end_second: int = betterproto.int32_field(8)


@dataclass
class ProtoOADynamicLeverage(betterproto.Message):
    leverage_id: int = betterproto.int64_field(1)
    tiers: list["ProtoOADynamicLeverageTier"] = betterproto.message_field(2)


@dataclass
class ProtoOADynamicLeverageTier(betterproto.Message):
    volume: int = betterproto.int64_field(1)
    leverage: int = betterproto.int32_field(2)


@dataclass
class ProtoOAPositionUnrealizedPnL(betterproto.Message):
    position_id: int = betterproto.int64_field(1)
    gross_unrealized_pn_l: int = betterproto.int64_field(2)
    net_unrealized_pn_l: int = betterproto.int64_field(3)
