# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: OpenApiCommonMessages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .OpenApiCommonModelMessages import ProtoPayloadType


@dataclass
class ProtoMessage(betterproto.Message):
    """
    * Base message that is used for all messages that are sent to/from Open API
    proxy of cTrader platform.
    """

    payload_type: int = betterproto.uint32_field(1)
    payload: bytes = betterproto.bytes_field(2)
    client_msg_id: str = betterproto.string_field(3)


@dataclass
class ProtoErrorRes(betterproto.Message):
    """* Error response that is sent from Open API proxy when error occurs."""

    payload_type: "ProtoPayloadType" = betterproto.enum_field(1)
    error_code: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    maintenance_end_timestamp: int = betterproto.uint64_field(4)


@dataclass
class ProtoHeartbeatEvent(betterproto.Message):
    """
    * Event that is sent from Open API proxy and can be used as criteria that
    connection is healthy when no other messages are sent by cTrader platform.
    Open API client can send this message when he needs to keep the connection
    open for a period without other messages longer than 30 seconds.
    """

    payload_type: "ProtoPayloadType" = betterproto.enum_field(1)
