# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: OpenApiCommonModelMessages.proto
# plugin: python-betterproto

import betterproto


class ProtoPayloadType(betterproto.Enum):
    """--- INTENSIVE COMMANDS 1 - 49 --- COMMON API 50 - 69"""

    # common intensive
    PROTO_MESSAGE = 5
    # common commands
    ERROR_RES = 50
    HEARTBEAT_EVENT = 51


class ProtoErrorCode(betterproto.Enum):
    """COMMON error codes 1 - 99"""

    UNKNOWN_ERROR = 1
    UNSUPPORTED_MESSAGE = 2
    INVALID_REQUEST = 3
    TIMEOUT_ERROR = 5
    ENTITY_NOT_FOUND = 6
    CANT_ROUTE_REQUEST = 7
    FRAME_TOO_LONG = 8
    MARKET_CLOSED = 9
    CONCURRENT_MODIFICATION = 10
    BLOCKED_PAYLOAD_TYPE = 11
