"""
Not yet implemented:
    - ProtoOAMarginCallUpdateEvent: Margin call threshold configuration changed.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

from ..enums import ExecutionType, OrderSide


@dataclass(frozen=True, slots=True)
class SpotEvent:
    """Price tick event.

    Emitted when bid/ask prices update for a subscribed symbol.

    Note: Prices are raw integer values from the server. To convert to
    actual prices, divide by 10^5 (e.g., 123000 = 1.23000). The exact
    decimal places depend on symbol configuration.

    Attributes:
        account_id: The cTID trader account ID.
        symbol_id: The symbol identifier.
        bid: Current bid price as raw integer, or None if unchanged.
        ask: Current ask price as raw integer, or None if unchanged.
        timestamp: Server timestamp of the tick.
    """

    account_id: int
    symbol_id: int
    bid: int | None
    ask: int | None
    timestamp: datetime


@dataclass(frozen=True, slots=True)
class ExecutionEvent:
    """Order execution event.

    Emitted when an order is accepted, filled, modified, canceled, etc.

    Attributes:
        account_id: The cTID trader account ID.
        execution_type: Type of execution (fill, cancel, etc.).
        order_id: The order identifier.
        position_id: The position identifier (if applicable).
        symbol_id: The symbol identifier.
        side: Order side (buy/sell).
        filled_volume: Volume filled in this execution (in cents).
        fill_price: Execution price (if filled).
        timestamp: Server timestamp of the execution.
        is_server_event: True if generated by server (e.g., stop-out).
        error_code: Error code if execution failed.
    """

    account_id: int
    execution_type: ExecutionType
    order_id: int
    position_id: int | None
    symbol_id: int
    side: OrderSide
    filled_volume: int | None
    fill_price: Decimal | None
    timestamp: datetime
    is_server_event: bool = False
    error_code: str | None = None


@dataclass(frozen=True, slots=True)
class OrderErrorEvent:
    """Order error event.

    Emitted when an order operation fails.

    Attributes:
        account_id: The cTID trader account ID.
        order_id: The order identifier (if available).
        position_id: The position identifier (if available).
        error_code: The error code from the server.
        description: Human-readable error description.
    """

    account_id: int
    order_id: int | None
    position_id: int | None
    error_code: str
    description: str


@dataclass(frozen=True, slots=True)
class TraderUpdateEvent:
    """Trader account update event.

    Emitted when account information changes (balance, leverage, etc.).

    Attributes:
        account_id: The cTID trader account ID.
        balance: Current account balance (raw, divide by 10^moneyDigits).
        leverage_in_cents: Account leverage in cents (5000 = 1:50).
        money_digits: Exponent for monetary values.
    """

    account_id: int
    balance: int
    leverage_in_cents: int | None
    money_digits: int


@dataclass(frozen=True, slots=True)
class MarginChangeEvent:
    """Position margin change event.

    Emitted when the margin allocated to a position changes.

    Attributes:
        account_id: The cTID trader account ID.
        position_id: The position identifier.
        used_margin: New margin value (raw, divide by 10^moneyDigits).
        money_digits: Exponent for monetary values.
    """

    account_id: int
    position_id: int
    used_margin: int
    money_digits: int


@dataclass(frozen=True, slots=True)
class DepthQuote:
    """Single depth of market quote."""

    quote_id: int
    price: int
    size: int
    is_bid: bool


@dataclass(frozen=True, slots=True)
class DepthEvent:
    """Market depth (order book) event.

    Emitted when the order book updates for a subscribed symbol.

    Attributes:
        account_id: The cTID trader account ID.
        symbol_id: The symbol identifier.
        new_quotes: New or updated quotes.
        deleted_quote_ids: IDs of quotes that were removed.
    """

    account_id: int
    symbol_id: int
    new_quotes: tuple[DepthQuote, ...]
    deleted_quote_ids: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class TokenInvalidatedEvent:
    """Token invalidated event.

    Emitted when access tokens are revoked or expired.

    Attributes:
        account_ids: List of affected account IDs.
        reason: Reason for invalidation.
    """

    account_ids: tuple[int, ...]
    reason: str


@dataclass(frozen=True, slots=True)
class ClientDisconnectEvent:
    """Client disconnect event.

    Emitted when the server terminates the client connection.

    Attributes:
        reason: Reason for disconnection.
    """

    reason: str


@dataclass(frozen=True, slots=True)
class AccountDisconnectEvent:
    """Account disconnect event.

    Emitted when a specific account session is terminated.

    Attributes:
        account_id: The cTID trader account ID.
    """

    account_id: int


@dataclass(frozen=True, slots=True)
class SymbolChangedEvent:
    """Symbol configuration changed event.

    Emitted when a symbol's configuration is updated (trading hours,
    margin requirements, spreads, etc.).

    Attributes:
        account_id: The cTID trader account ID.
        symbol_ids: List of symbol IDs that changed.
    """

    account_id: int
    symbol_ids: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class TrailingStopChangedEvent:
    """Trailing stop loss level changed event.

    Emitted when a trailing stop loss price is updated due to
    favorable price movement.

    Attributes:
        account_id: The cTID trader account ID.
        position_id: The position identifier.
        order_id: The stop loss order identifier.
        stop_price: New stop loss price.
        timestamp: Server timestamp of the update.
    """

    account_id: int
    position_id: int
    order_id: int
    stop_price: Decimal
    timestamp: datetime


@dataclass(frozen=True, slots=True)
class MarginCallTriggerEvent:
    """Margin call triggered event.

    Emitted when account margin level reaches a configured threshold.
    Sent at most once every 10 minutes per threshold to avoid spam.

    Attributes:
        account_id: The cTID trader account ID.
        margin_call_type: Type of margin call (1, 2, or 3 for different thresholds).
        margin_level_threshold: The threshold that was breached (percentage).
    """

    account_id: int
    margin_call_type: int
    margin_level_threshold: Decimal


@dataclass(frozen=True, slots=True)
class PnLChangeEvent:
    """Unrealized PnL change event.

    Emitted when unrealized profit/loss changes due to market movement.
    Requires subscription via ProtoOAv1PnLChangeSubscribeReq.

    Attributes:
        account_id: The cTID trader account ID.
        gross_unrealized_pnl: Gross unrealized PnL (raw, divide by 10^moneyDigits).
        net_unrealized_pnl: Net unrealized PnL (raw, divide by 10^moneyDigits).
        money_digits: Exponent for monetary values.
    """

    account_id: int
    gross_unrealized_pnl: int
    net_unrealized_pnl: int
    money_digits: int


# Type alias for any event type
type Event = (
    SpotEvent
    | ExecutionEvent
    | OrderErrorEvent
    | TraderUpdateEvent
    | MarginChangeEvent
    | DepthEvent
    | TokenInvalidatedEvent
    | ClientDisconnectEvent
    | AccountDisconnectEvent
    | SymbolChangedEvent
    | TrailingStopChangedEvent
    | MarginCallTriggerEvent
    | PnLChangeEvent
)
