"""
Not yet implemented:
    - ProtoOAMarginCallUpdateEvent: Margin call threshold configuration changed.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

from ..enums import AuthTrigger, ExecutionType, OrderSide
from ..exceptions import TokenRefreshError
from ..models import Trendbar


@dataclass(frozen=True, slots=True)
class SpotEvent:
    """Price tick event.

    Emitted when bid/ask prices update for a subscribed symbol.

    Attributes:
        account_id: The cTID trader account ID.
        symbol_id: The symbol identifier.
        bid: Current bid price
        ask: Current ask price
        trendbar: Live trend bar. Only populated if subscribed to trendbar updates via MarketDataAPI.subscribe_trendbars
        timestamp: Server timestamp of the tick.
    """

    account_id: int
    symbol_id: int
    bid: Decimal | None
    ask: Decimal | None
    trendbar: list[Trendbar]
    timestamp: datetime


@dataclass(frozen=True, slots=True)
class ExecutionEvent:
    """Order execution event.

    Emitted when an order is accepted, filled, modified, canceled, etc.

    Attributes:
        account_id: The cTID trader account ID.
        execution_type: Type of execution (fill, cancel, etc.).
        order_id: The order identifier.
        position_id: The position identifier (if applicable).
        symbol_id: The symbol identifier.
        side: Order side (buy/sell).
        filled_volume: Volume filled in this execution (in cents).
        fill_price: Execution price (if filled).
        timestamp: Server timestamp of the execution.
        is_server_event: True if generated by server (e.g., stop-out).
        error_code: Error code if execution failed.
    """

    account_id: int
    execution_type: ExecutionType
    order_id: int
    position_id: int | None
    symbol_id: int
    side: OrderSide
    filled_volume: int | None
    fill_price: Decimal | None
    timestamp: datetime
    is_server_event: bool = False
    error_code: str | None = None


@dataclass(frozen=True, slots=True)
class OrderErrorEvent:
    """Order error event.

    Emitted when an order operation fails.

    Attributes:
        account_id: The cTID trader account ID.
        order_id: The order identifier (if available).
        position_id: The position identifier (if available).
        error_code: The error code from the server.
        description: Human-readable error description.
    """

    account_id: int
    order_id: int | None
    position_id: int | None
    error_code: str
    description: str


@dataclass(frozen=True, slots=True)
class TraderUpdateEvent:
    """Trader account update event.

    Emitted when account information changes (balance, leverage, etc.).

    Attributes:
        account_id: The cTID trader account ID.
        balance: Current account balance (raw, divide by 10^moneyDigits).
        leverage_in_cents: Account leverage in cents (5000 = 1:50).
        money_digits: Exponent for monetary values.
    """

    account_id: int
    balance: int
    leverage_in_cents: int | None
    money_digits: int


@dataclass(frozen=True, slots=True)
class MarginChangeEvent:
    """Position margin change event.

    Emitted when the margin allocated to a position changes.

    Attributes:
        account_id: The cTID trader account ID.
        position_id: The position identifier.
        used_margin: New margin value (raw, divide by 10^moneyDigits).
        money_digits: Exponent for monetary values.
    """

    account_id: int
    position_id: int
    used_margin: int
    money_digits: int


@dataclass(frozen=True, slots=True)
class DepthQuote:
    """
    Single depth of market quote.

    Attributes:
        quote_id: Unique identifier for the quote (used for updates/deletions).
        price: Quote price (raw integer, divide by 10^priceDigits).
        size: Quote size (volume in cents).
        is_bid: True if this is a bid quote, False if it's an ask quote.
    """

    quote_id: int
    price: int
    size: int
    is_bid: bool


@dataclass(frozen=True, slots=True)
class DepthEvent:
    """Market depth (order book) event.

    Emitted when the order book updates for a subscribed symbol.

    Attributes:
        account_id: The cTID trader account ID.
        symbol_id: The symbol identifier.
        new_quotes: New or updated quotes.
        deleted_quote_ids: IDs of quotes that were removed.
    """

    account_id: int
    symbol_id: int
    new_quotes: tuple[DepthQuote, ...]
    deleted_quote_ids: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class TokenInvalidatedEvent:
    """Token invalidated event.

    Emitted when access tokens are revoked or expired.

    Attributes:
        account_ids: List of affected account IDs.
        reason: Reason for invalidation.
    """

    account_ids: tuple[int, ...]
    reason: str


@dataclass(frozen=True, slots=True)
class TokenRefreshFailedEvent:
    """Token refresh failed event.

    Emitted when an access token could not be refreshed after all retries.
    The old credentials are kept and the client retries on the next refresh
    check, so a transient failure recovers on its own. A persistent failure
    means the refresh token is no longer usable and the account must be
    re-authorized out of band.

    Attributes:
        account_id: The cTID trader account ID.
        error: The refresh failure, including its underlying cause.
    """

    account_id: int
    error: TokenRefreshError


@dataclass(frozen=True, slots=True)
class SubscriptionRestoreFailedEvent:
    """Subscription restore failed event.

    Emitted when standing market data subscriptions could not be re-applied
    after a session was re-established. Restoration stops at the first failure,
    so subscriptions after it in the sequence are also missing.

    The intent is kept, so the next reconnection tries again. Until then the
    account receives no data for the affected symbols, and a consumer that
    needs it sooner should re-subscribe from a handler.

    Attributes:
        account_id: The cTID trader account ID.
        error: The failure that stopped restoration.
    """

    account_id: int
    error: Exception


@dataclass(frozen=True, slots=True)
class ClientDisconnectEvent:
    """Client disconnect event.

    Emitted when the server terminates the client connection.

    Attributes:
        reason: Reason for disconnection.
    """

    reason: str


@dataclass(frozen=True, slots=True)
class AccountDisconnectEvent:
    """Account disconnect event.

    Emitted when an account's session has been terminated by the server while
    the underlying connection stays up, and could not be re-established on the
    spot. The client keeps re-authenticating on the existing connection with
    backoff until it succeeds, then emits a ReadyEvent; no user action is
    required to restore the session.

    The server also reports a disconnect whenever the token behind an
    authorization is rotated, for a session it has not actually ended. Those
    reports are checked against the server and discarded, so they do not appear
    here — every event published is a drop that outlived a re-authentication
    attempt.

    Attributes:
        account_id: The cTID trader account ID.
    """

    account_id: int


@dataclass(frozen=True, slots=True)
class SymbolChangedEvent:
    """Symbol configuration changed event.

    Emitted when a symbol's configuration is updated (trading hours,
    margin requirements, spreads, etc.).

    Attributes:
        account_id: The cTID trader account ID.
        symbol_ids: List of symbol IDs that changed.
    """

    account_id: int
    symbol_ids: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class TrailingStopChangedEvent:
    """Trailing stop loss level changed event.

    Emitted when a trailing stop loss price is updated due to
    favorable price movement.

    Attributes:
        account_id: The cTID trader account ID.
        position_id: The position identifier.
        order_id: The stop loss order identifier.
        stop_price: New stop loss price.
        timestamp: Server timestamp of the update.
    """

    account_id: int
    position_id: int
    order_id: int
    stop_price: Decimal
    timestamp: datetime


@dataclass(frozen=True, slots=True)
class MarginCallTriggerEvent:
    """Margin call triggered event.

    Emitted when account margin level reaches a configured threshold.
    Sent at most once every 10 minutes per threshold to avoid spam.

    Attributes:
        account_id: The cTID trader account ID.
        margin_call_type: Type of margin call (1, 2, or 3 for different thresholds).
        margin_level_threshold: The threshold that was breached (percentage).
    """

    account_id: int
    margin_call_type: int
    margin_level_threshold: Decimal


@dataclass(frozen=True, slots=True)
class ReconnectedEvent:
    """Emitted after automatic reconnection and re-authentication.

    When a connection is lost and automatically restored, the client
    re-authenticates the app and all previously authenticated accounts.
    Subscriptions (spots, trendbars, depth) are NOT automatically restored
    and should be handled using ReadyEvent instead.
    Use this event for any custom logic that depends on reconnection, such as logging or alerting.

    Attributes:
        app_auth_restored: Whether app authentication succeeded on the attempt
            this event reports. False is not final: the client keeps retrying
            with backoff, and announces each account it restores afterwards with
            a ReadyEvent. Check `client.auth.is_app_authenticated` for the
            state now.
        restored_accounts: Account IDs that were successfully re-authenticated.
            Empty when app authentication failed, since nothing can be
            authorized before it succeeds — not a report that they were lost.
        failed_accounts: Accounts that failed, as (account_id, error_message) tuples.
    """

    app_auth_restored: bool
    restored_accounts: tuple[int, ...]
    failed_accounts: tuple[tuple[int, str], ...]


@dataclass(frozen=True, slots=True)
class ReadyEvent:
    """Emitted when an account is authenticated and ready for use.

    Fired whenever a server-side session is (re)established and subscriptions
    must be (re)applied: initial authentication, re-authentication after a
    transport reconnection, and recovery after a server-side account
    disconnect. It is not fired for token-refresh re-auth, where the session
    and its subscriptions remain intact. Use this to set up subscriptions that
    should persist across reconnections.

    Attributes:
        account_id: The cTID trader account ID that is now ready.
        trigger: Why the session was established. Never TOKEN_REFRESH.
    """

    account_id: int
    trigger: AuthTrigger

    @property
    def is_reconnect(self) -> bool:
        """True if this follows a reconnection or account-disconnect recovery."""
        return self.trigger is not AuthTrigger.INITIAL


# Type alias for any event type
type Event = (
    SpotEvent
    | ExecutionEvent
    | OrderErrorEvent
    | TraderUpdateEvent
    | MarginChangeEvent
    | DepthEvent
    | TokenInvalidatedEvent
    | TokenRefreshFailedEvent
    | SubscriptionRestoreFailedEvent
    | ClientDisconnectEvent
    | AccountDisconnectEvent
    | SymbolChangedEvent
    | TrailingStopChangedEvent
    | MarginCallTriggerEvent
    | ReconnectedEvent
    | ReadyEvent
)
